# Generated by Django 4.1.5 on 2023-02-01 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_hospitation_date', models.DateField(verbose_name='last hospitation Date')),
                ('academic_title', models.TextField(verbose_name='academic Title')),
                ('specialization', models.TextField(verbose_name='specialization')),
                ('first_name', models.TextField(verbose_name='first Name')),
                ('last_name', models.TextField(verbose_name='last Name')),
                ('belongs_to_WZHZ', models.BooleanField(default=False, verbose_name='belongs to WZHZ')),
                ('appointment_to_WZHZ_date', models.DateField(blank=True, null=True, verbose_name='appointment to WZHZ Date')),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_specialization', models.TextField(verbose_name='required Specialization')),
                ('code', models.TextField(verbose_name='code')),
                ('class_type', models.TextField(verbose_name='class Type')),
                ('name', models.TextField(verbose_name='name')),
                ('time_and_location', models.TextField(verbose_name='time and Location')),
                ('ECTS', models.IntegerField(verbose_name='ECTS')),
                ('teaching_method', models.TextField(verbose_name='teaching Method')),
                ('study_program', models.TextField(verbose_name='study Program')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitation_manager.academicteacher', verbose_name='teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ProtocolAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='lodging date')),
                ('reason', models.TextField(verbose_name='reason')),
                ('status', models.CharField(choices=[('OD', 'odrzucone'), ('ZA', 'zatwierdzone'), ('OC', 'oczekuje')], default='OC', max_length=2, verbose_name='status')),
                ('dean_response', models.TextField(blank=True, null=True, verbose_name='dean response')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitation_manager.academicteacher', verbose_name='issuer')),
            ],
        ),
        migrations.CreateModel(
            name='HospitationTeam',
            fields=[
                ('number', models.BigAutoField(primary_key=True, serialize=False, verbose_name='number')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='creation Date')),
                ('academic_teacher1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_teacher1', to='hospitation_manager.academicteacher', verbose_name='academic Teacher 1')),
                ('academic_teacher2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_teacher2', to='hospitation_manager.academicteacher', verbose_name='academic Teacher 2')),
            ],
        ),
        migrations.CreateModel(
            name='HospitationProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='lodging date')),
                ('protocol_content', models.TextField(verbose_name='content of protocol')),
                ('is_appeal_lodged', models.BooleanField(default=False, verbose_name='is appeal lodged?')),
                ('appeal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitation_manager.protocolappeal', verbose_name='appeal')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitation_manager.academicteacher', verbose_name='issuer')),
            ],
        ),
        migrations.CreateModel(
            name='Hospitation',
            fields=[
                ('number', models.BigAutoField(primary_key=True, serialize=False, verbose_name='number')),
                ('hospitation_date', models.DateField(verbose_name='hospitation Date')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='date')),
                ('status', models.CharField(choices=[('Z', 'Przeprowadzona'), ('O', 'Odwołana'), ('W', 'Oczekuje na przeprowadzenie')], default='W', max_length=1, verbose_name='status')),
                ('associated_protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitation_manager.hospitationprotocol', verbose_name='associated protocol')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitation_manager.classes', verbose_name='classes')),
                ('hospitation_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitation_manager.hospitationteam', verbose_name='hospitation Team')),
            ],
        ),
    ]
