# Generated by Django 4.1.5 on 2023-02-01 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitation_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitation',
            name='associated_protocol',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitation_manager.hospitationprotocol', verbose_name='associated protocol'),
        ),
        migrations.AlterField(
            model_name='hospitationprotocol',
            name='appeal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitation_manager.protocolappeal', verbose_name='appeal'),
        ),
    ]
