# Generated by Django 4.1.5 on 2023-02-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitation_manager', '0002_alter_hospitation_associated_protocol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicteacher',
            name='last_hospitation_date',
            field=models.DateField(blank=True, null=True, verbose_name='last hospitation Date'),
        ),
    ]
