# Generated by Django 4.1.5 on 2023-02-02 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitation_manager', '0003_alter_academicteacher_last_hospitation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicteacher',
            name='academic_title',
            field=models.TextField(blank=True, verbose_name='academic Title'),
        ),
        migrations.AlterField(
            model_name='academicteacher',
            name='specialization',
            field=models.TextField(blank=True, verbose_name='specialization'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='required_specialization',
            field=models.TextField(blank=True, verbose_name='required Specialization'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='study_program',
            field=models.TextField(blank=True, verbose_name='study Program'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitation_manager.academicteacher', verbose_name='teacher'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='teaching_method',
            field=models.TextField(blank=True, verbose_name='teaching Method'),
        ),
    ]
